### ISSUE TITLE
How do we run this?

### ISSUE THREAD

**Issue by 0pankajkumar** [crocup/Fenix-VM#95]
Hi,
Nice work here. I wanted to see this in action. I see some docker config files which makes a lot of things easier. But still, Can you add running instructions as well.

**Comment by crocup** [comment]
Hi, thanks! The program is under development. One of the principles is that it should be easy to install and use. I do it myself and in my spare time. I plan to add installation and usage instructions, as well as release a preview version next month. But there is still a lot of work to be done. Thank you for understanding!
